name: lede
on: push
jobs:
 build:
  runs-on: ubuntu-18.04
  steps:
  - name: 环境
    run: |
     sudo apt update
     sudo apt -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
     git clone https://github.com/coolsnowwolf/lede
  - name: 自定义软件
    run: |
     cd lede
     echo 'src-git kenzo https://github.com/kenzok8/openwrt-packages'>>feeds.conf.default
     echo 'src-git small https://github.com/kenzok8/small'>>feeds.conf.default
  - name: 安装软件
    run: |
     ./scripts/feeds update -a
     ./scripts/feeds install -a
  - name: 配置.config
    run: |
     mv mine.config lede/.config
  - name: 下载软件包
    run: |
     cd lede && make download -j8
  - name: 编译
    run: |
     cd lede
     make -j$(($(nproc) + 1)) V=s
  - name: 整理
    run: |
     cd lede/bin/targets/*/*
     rm -rf packages
  - name: 上传
    uses: actions/checkout@v2
    with:
     name: lede
     path: lede/bin/targets/*/*/
